### ISSUE TITLE
The build fails due to incorrect usage of main key in package.json

### ISSUE THREAD

**Issue by varghesethomase** [STORIS/material-ui-scrollable-tabs#2]
On installing from npm, the current main: points to './index.js' which isn't the entry point, but it must be './Tabs/index.js'

**Comment by shawnmcknight** [comment]
@varghesethomase All examples of material-ui that I had previously encountered were importing the components as named modules from their respective component folders (e.g. `import {Tabs, Tab} from 'material-ui/Tabs';`).  I made this library match that pattern so you should be able to `import {Tabs, Tab} from 'material-ui-scrollable-tabs/Tabs';`.

With that said, I now see that you can also import material-ui components from the main index.js.  I will take care of making this work in the next update.  In the meantime, try the alternative syntax I show above and let me know if you have any problems.

**Comment by shawnmcknight** [comment]
`develop` branch has been pushed which includes an update to the build process which should resolve this issue.  It'll be included in the next release.

**Comment by varghesethomase** [comment]
@shawnmcknight  thanks for the quick fix. Though the issue occurred to me while i included it via yarn in the react-boilerplate app. Including this file, there occurred a module not found error, as in th package.json the main file pointed to ./index.js which never existed. Instead the ./index.js file existed in Tabs/index.js. This is the why I raised this issue. When i looked into material-ui repo, there is a base index.js file where all the components had been exported from, which never exited in your project.
