### ISSUE TITLE
Accessing PropTypes via the main React package is deprecated

### ISSUE THREAD

**Issue by ErreMalote** [STORIS/material-ui-scrollable-tabs#8]
PropTypes has its own module. importing from react is deprecated is it a possibility to correct that? react 16 is out and cant use it if this is not corrected.

**Comment by paulty77** [comment]
Same warning for me... I use React 0.15.6

It's in component "tabs"

Tab.contextTypes = {
  muiTheme: _react.PropTypes.object.isRequired
};

lowPriorityWarning.js:40 Warning: Accessing PropTypes via the main React package is deprecated, and will be removed in  React v16.0. Use the latest available v15.* prop-types package from npm instead. For info on usage, compatibility, migration and more, see https://fb.me/prop-types-docs

**Comment by shawnmcknight** [comment]
Release 2.0.0 has been published and PropTypes has been migrated to the standalone prop-types library.
